wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1663813844.287353
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.13.1
      8:
      - 5
seed:
  desc: null
  value: 897
wandb_entity:
  desc: null
  value: cs532-2022
wandb_logging:
  desc: null
  value: true
wandb_project:
  desc: null
  value: HW1-Q3
