# Weights and biases
wandb_run: False

# Directory structure
base_dir: '../CS532-HW2' # NOTE: This path should be relative to the daphne path!
daphne_dir: '../daphne' # NOTE: This path should be relative to the homework directory!

# Tests and programs to run
deterministic_tests: []
probabilistic_tests: [5]
HW2_programs: []

# Daphne (re)compilation
compile: False

# Evaluation method
# mode: 'desugar'
mode: 'graph'

# Inference
num_samples: 1
