# Weights and biases
wandb_run: True

# Directory structure
base_dir: '../CS532-HW3' # NOTE: This path should be relative to the daphne path!
daphne_dir: '../daphne' # NOTE: This path should be relative to the homework directory!

# Tests and programs to run
deterministic_tests: []
probabilistic_tests: []
HW2_programs: [1,2,3,4,5]

# Daphne (re)compilation
compile: False

# Evaluation method
mode: 'desugar'
# mode: 'graph'

# Inference
num_samples: 1e3
