wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1663542023.476684
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.13.1
      8:
      - 5
seed:
  desc: null
  value: 1002
setup:
  desc: null
  value:
    mode: online
    project: hydra-example
    wandb_entity: elvis-cai
wandb_entity:
  desc: null
  value: elvis_cai
wandb_logging:
  desc: null
  value: 'True'
wandb_project:
  desc: null
  value: hw1
watch:
  desc: null
  value:
    log: all
    log_freq: 100
